# Generated by Django 5.1.2 on 2024-11-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
